consul-conf:
  image: husseingalal/consul-config
  labels:
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - consul
  net: "container:consul"
consul:
  image: husseingalal/consul:ui
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.sidekicks: consul-conf
  environment:
    WEB_UI: '${ui}'
  volumes:
    - /opt/rancher/ssl
    - /opt/rancher/config
    - /var/consul
